---
# =============================================================================
# Vault-encrypted secrets
# Encrypt this file with: ansible-vault encrypt group_vars/vault.yml
# =============================================================================

vault_postgresql_superuser_password: "SecurePostgresPassword123!"
vault_postgresql_replicator_password: "SecureReplicatorPassword123!"
vault_postgresql_admin_password: "SecureAdminPassword123!"
