---
# =============================================================================
# roles/pgbackrest/defaults/main.yml
# =============================================================================

# Repository
pgbackrest_repo_path: /var/lib/pgbackrest
pgbackrest_retention_full: 2
pgbackrest_retention_diff: 7

# Performance
pgbackrest_process_max: 4
pgbackrest_compress_type: zst
pgbackrest_compress_level: 3

# Logging
pgbackrest_log_dir: /var/log/pgbackrest
pgbackrest_log_level_console: info
pgbackrest_log_level_file: detail

# Config
pgbackrest_config_dir: /etc/pgbackrest
pgbackrest_config_file: "{{ pgbackrest_config_dir }}/pgbackrest.conf"
