---
patroni_cluster_name: "postgres-cluster"
patroni_namespace: "/db/"
patroni_restapi_port: 8008
patroni_config_dir: "/etc/patroni"
patroni_home_dir: "/var/lib/patroni"
patroni_log_dir: "/var/log/patroni"
patroni_venv_path: "/opt/patroni-venv"
patroni_ttl: 30
patroni_loop_wait: 10
patroni_retry_timeout: 10
patroni_max_lag_on_failover: 1048576
