#!/usr/bin/env python3
"""
refresh_inventory.py — regenerate hosts.ini from inventory/gcp_instances.json

Run any time hosts.ini is empty or stale:
    python3 refresh_inventory.py

Works correctly regardless of which directory you run it from.
"""
import json, os, sys

# All paths resolve relative to THIS script's location — not cwd
SCRIPT_DIR  = os.path.dirname(os.path.realpath(__file__))
JSON_FILE   = os.path.join(SCRIPT_DIR, 'inventory', 'gcp_instances.json')
HOSTS_FILE  = os.path.join(SCRIPT_DIR, 'inventory', 'hosts.ini')
VENV_PYTHON = os.path.join(SCRIPT_DIR, '.venv', 'bin', 'python3')

# ── Load instances ────────────────────────────────────────────────────────────
if not os.path.exists(JSON_FILE):
    print(f"ERROR: {JSON_FILE} not found.")
    print("       Run 'just provision' first to create instances.")
    sys.exit(1)

with open(JSON_FILE) as f:
    instances = json.load(f)

if not instances:
    print(f"ERROR: {JSON_FILE} is empty.")
    print("       Run 'just provision' first to create instances.")
    sys.exit(1)

# ── Split by role ─────────────────────────────────────────────────────────────
pg_nodes = [i for i in instances if i['name'].startswith('pg-node')]
haproxy  = [i for i in instances if i['name'].startswith('ha-proxy')]

def host_line(inst):
    ext = inst['networkInterfaces'][0]['accessConfigs'][0]['natIP']
    iip = inst['networkInterfaces'][0]['networkIP']
    return f"{inst['name']} ansible_host={ext} internal_ip={iip}"

# ── Read user/key from environment ───────────────────────────────────────────
user    = os.environ.get('USER', 'ubuntu')
home    = os.environ.get('HOME', os.path.expanduser('~'))
ssh_key = os.path.join(home, '.ssh', 'id_rsa')

# ── Write hosts.ini ───────────────────────────────────────────────────────────
content = f"""\
# ============================================================
# Patroni HA Cluster Inventory
# Generated by refresh_inventory.py — do not edit manually
# ============================================================

[all:vars]
ansible_user={user}
ansible_ssh_private_key_file={ssh_key}
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local ansible_python_interpreter={VENV_PYTHON}

[patroni_cluster]
{chr(10).join(host_line(i) for i in pg_nodes)}

[etcd_cluster]
{chr(10).join(host_line(i) for i in pg_nodes)}

[haproxy]
{chr(10).join(host_line(i) for i in haproxy)}

[keepalived]
{chr(10).join(host_line(i) for i in haproxy)}

[all:children]
patroni_cluster
etcd_cluster
haproxy
keepalived
"""

with open(HOSTS_FILE, 'w') as f:
    f.write(content)

print(f"Written : {HOSTS_FILE}")
print(f"User    : {user}")
print(f"Venv    : {VENV_PYTHON}")
print(f"Nodes   : {[i['name'] for i in pg_nodes + haproxy]}")
